'use client';

import type { AdvanceQuota } from '../lib/preferences';
import { HelpTip } from './help-tip';

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const distributions = { balanced: 'Spread daily', weighted: 'By day priority', concentrated: 'Group days', quality: 'Quality first' };

export function AdvanceQuotaFields({ value, rooms, onChange }: { value: AdvanceQuota; rooms: string[]; onChange: (value: AdvanceQuota) => void }) {
  const change = (patch: Partial<AdvanceQuota>) => onChange({ ...value, ...patch });
  function move<T>(items: T[], index: number, direction: number): T[] {
    const next = [...items]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; return next;
  }
  return <div className="advance-quota-fields">
    <p className="quiet-muted">Choose how to spend your rolling advance hours. Existing bookings stay in place.</p>
    <div><label>Distribution<select aria-label="Distribution" value={value.distribution} onChange={e => change({ distribution: e.target.value as AdvanceQuota['distribution'] })}>{Object.entries(distributions).map(([key, title]) => <option key={key} value={key}>{title}</option>)}</select></label><HelpTip label="Distribution">Spread protects a useful block each day. Day priorities aim for proportionally more time on higher-priority days. Grouping favours fewer days; quality favours your ranked rooms and periods.</HelpTip></div>
    <div><label>Daily block to protect (minutes)<input type="number" min="30" max="120" step="15" value={value.anchor_minutes} onChange={e => change({ anchor_minutes: Number(e.target.value) })} /></label><HelpTip label="Daily block to protect">An aim for spread and day-priority planning, not a guaranteed booking or minimum. Six hours shared across seven days may mean 45–60 minutes per day.</HelpTip></div>
    <label>Preferred advance session<select aria-label="Preferred advance session" value={value.block_minutes} onChange={e => change({ block_minutes: Number(e.target.value) })}>{[[0, 'General strategy'], [30, '30 minutes'], [60, '1 hour'], [90, '1½ hours'], [120, '2 hours']].map(([n, title]) => <option key={n} value={n}>{title}</option>)}</select></label>
    <details><summary>Rooms and time periods</summary>
      <label>Rooms to use<select aria-label="Rooms to use" value={value.room_mode} onChange={e => change({ room_mode: e.target.value as AdvanceQuota['room_mode'] })}><option value="top">Top favourites</option><option value="selected">Choose rooms</option><option value="all">All favourites</option></select></label>
      {value.room_mode === 'top' && <label>Number of top rooms<input type="number" min="1" max="100" step="1" value={value.top_room_count} onChange={e => change({ top_room_count: Number(e.target.value) })} /></label>}
      {value.room_mode === 'selected' && <>
        <ol className="advance-ranked">{value.room_order.map((room, i) => <li key={room}><span>{room}{!rooms.includes(room) ? ' (currently excluded)' : ''}</span><div className="advance-row-actions"><button type="button" aria-label={`Move ${room} up`} disabled={!i} onClick={() => change({ room_order: move(value.room_order, i, -1) })}>↑</button><button type="button" aria-label={`Move ${room} down`} disabled={i === value.room_order.length - 1} onClick={() => change({ room_order: move(value.room_order, i, 1) })}>↓</button><button type="button" aria-label={`Remove ${room}`} onClick={() => change({ room_order: value.room_order.filter(r => r !== room) })}>Remove</button></div></li>)}</ol>
        <label>Add advance room<select aria-label="Add advance room" value="" onChange={e => { if (e.target.value) change({ room_order: [...value.room_order, e.target.value] }); }}><option value="">Choose a room…</option>{rooms.filter(room => !value.room_order.includes(room)).map(room => <option key={room}>{room}</option>)}</select></label>
      </>}
      {value.room_mode !== 'all' && <label><input type="checkbox" checked={value.room_fallback} onChange={e => change({ room_fallback: e.target.checked })} />Allow other eligible rooms as fallbacks</label>}
      <div><label>Room or time priority<select aria-label="Room or time priority" value={value.priority_mode} onChange={e => change({ priority_mode: e.target.value as AdvanceQuota['priority_mode'] })}><option value="inherit">General strategy</option><option value="time_first">Time first</option><option value="room_first">Room first</option></select></label><HelpTip label="Advance priorities">Only advance bookings use these priorities. General room exclusions, strict hours, daily targets and College limits still apply.</HelpTip></div>
      <div className="section-heading"><strong>Ranked time periods</strong><HelpTip label="Ranked time periods">Earlier rows have higher priority. With no custom periods, use Preferred times. Periods replace soft preferred hours only; strict hours still apply.</HelpTip></div>
      {!value.periods.length && <p className="quiet-muted">Using your Preferred times.</p>}
      {value.periods.map((period, i) => <fieldset key={i} className="advance-period"><legend>Priority {i + 1}</legend><div className="advance-days">{days.map((day, d) => <label key={day}><input type="checkbox" aria-label={`${day} for period ${i + 1}`} checked={period.days.includes(d)} onChange={e => change({ periods: value.periods.map((p, index) => index === i ? { ...p, days: e.target.checked ? [...p.days, d].sort((a, b) => a - b) : p.days.filter(n => n !== d) } : p) })} />{day.slice(0, 3)}</label>)}</div><div className="advance-times">{(['start', 'end'] as const).map(key => <label key={key}>{key === 'start' ? 'From' : 'Until'}<input type="time" required step="900" aria-label={`${key} for period ${i + 1}`} value={period[key]} onChange={e => change({ periods: value.periods.map((p, index) => index === i ? { ...p, [key]: e.target.value } : p) })} /></label>)}</div><div className="advance-row-actions"><button type="button" disabled={!i} aria-label={`Move period ${i + 1} up`} onClick={() => change({ periods: move(value.periods, i, -1) })}>↑</button><button type="button" disabled={i === value.periods.length - 1} aria-label={`Move period ${i + 1} down`} onClick={() => change({ periods: move(value.periods, i, 1) })}>↓</button><button type="button" onClick={() => change({ periods: value.periods.filter((_, index) => index !== i) })}>Remove period {i + 1}</button></div></fieldset>)}
      <button type="button" className="quiet-secondary" disabled={value.periods.length >= 14} onClick={() => change({ periods: [...value.periods, { days: [0, 1, 2, 3, 4, 5, 6], start: '16:00', end: '18:00' }] })}>Add time period</button>
      <label>Outside these periods<select aria-label="Outside these periods" value={value.period_mode} onChange={e => change({ period_mode: e.target.value as AdvanceQuota['period_mode'] })}><option value="prefer">Allow alternatives</option><option value="only">Only these periods</option></select></label>
    </details>
    <details><summary>Day priorities and limits</summary><p className="quiet-muted">Priority 0 stops advance bookings on that weekday. Other weights apply to “By day priority”. Limits include time already booked or reserved for extensions.</p>
      {days.map((day, i) => <div className="advance-day-row" key={day}><strong>{day}</strong><label>Priority (0–10)<input aria-label={`${day} priority`} type="number" min="0" max="10" step="1" value={value.day_weights[i]} onChange={e => change({ day_weights: value.day_weights.map((n, j) => i === j ? Number(e.target.value) : n) })} /></label><label>Limit (minutes)<input aria-label={`${day} advance limit (minutes)`} type="number" min="0" max="720" step="15" value={value.day_caps_minutes[i]} onChange={e => change({ day_caps_minutes: value.day_caps_minutes.map((n, j) => i === j ? Number(e.target.value) : n) })} /></label></div>)}
      <p className="quiet-muted">Limit 0 uses your daily practice target. Last-minute booking can still fill the rest of that target.</p>
    </details>
    <details><summary>Waiting and credit reserve</summary>
      <div><label><input type="checkbox" checked={value.wait_for_opening} onChange={e => change({ wait_for_opening: e.target.checked })} />Plan for rooms whose booking window opens later</label><HelpTip label="Room booking windows">Keep an allocation for a suitable future opening, including shorter room horizons. Turning this off considers only rooms bookable now. Availability is checked again before booking.</HelpTip></div>
      <div><label>Keep advance credit unused (minutes)<input type="number" min="0" max="10080" step="15" value={value.reserve_minutes} onChange={e => change({ reserve_minutes: Number(e.target.value) })} /></label><HelpTip label="Credit reserve">Withhold this much available credit from advance planning. Imminent and last-minute practice may still use it; ASIMUT charges remaining credit normally.</HelpTip></div>
      <div><label>Release credit for last-minute practice (minutes before start)<input type="number" placeholder="General strategy" min="0" max="1440" step="15" value={value.fallback_lead_minutes ?? ''} onChange={e => change({ fallback_lead_minutes: e.target.value === '' ? null : Number(e.target.value) })} /></label><HelpTip label="Release credit">When advance credit remains, wait until this long before a last-minute session starts before spending it. Blank uses Booking strategy. Exhausted quota uses the College’s five-hour window.</HelpTip></div>
      <label>Equal choices between dates<select aria-label="Equal choices between dates" value={value.date_order} onChange={e => change({ date_order: e.target.value as AdvanceQuota['date_order'] })}><option value="inherit">General strategy</option><option value="nearest">Nearest first</option><option value="furthest">Furthest first</option></select></label>
    </details>
  </div>;
}
